services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=project-db-cgi.smhrd.com
      - DATABASE_PORT=3307
      - DATABASE_USER=ohi0
      - DATABASE_PASSWORD=smart123!
      - DATABASE_NAME=ohi0
      - TZ=Asia/Seoul  # 한국 시간대 설정 추가
    networks:
      - mynetwork

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./flask:/app
    networks:
      - mynetwork
    depends_on:
      - backend

  flask2:
    build:
      context: ./flask2
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # FastAPI 서버 포트 매핑
    volumes:
      - ./flask2:/app  # flask2 폴더를 컨테이너 내부 /app에 매핑
    networks:
      - mynetwork
    depends_on:
      - backend

volumes:
  db_data:

networks:
  mynetwork:
